[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Cấu hình tốc độ gỡ lỗi và nạp code
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    4-20ma/ModbusMaster@^2.0.1
    knolleary/PubSubClient@^2.8
